version: 3
projects:
  - name: preliminary
    dir: terraform/preliminary
    workflow: default
    autoplan:
      when_modified: ["*.tf", "*.tfvars", "*.tf.json"]
      enabled: true
    apply_requirements: [approved]

  - name: implementation
    dir: terraform/implementation
    workflow: default
    autoplan:
      when_modified: ["*.tf", "*.tfvars", "*.tf.json"]
      enabled: true
    apply_requirements: [approved]

workflows:
  default:
    plan:
      steps:
        - init
        - plan
    apply:
      steps:
        - apply
