[all]
master ansible_host=10.10.1.50 ip=10.10.1.50 ansible_user=master ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q worker@84.252.128.120 -i ~/.ssh/id_ed25519"'

worker-1 ansible_host=10.10.2.29 ip=10.10.2.29 ansible_user=worker ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q worker@84.252.128.120 -i ~/.ssh/id_ed25519"'
worker-2 ansible_host=10.10.3.28 ip=10.10.3.28 ansible_user=worker ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q worker@84.252.128.120 -i ~/.ssh/id_ed25519"'

[bastion]
bastion ansible_host=84.252.128.120 ansible_user=worker ansible_ssh_private_key_file=~/.ssh/id_ed25519

[metallb-access]
bastion-privat ansible_host=10.10.4.7 ansible_user=worker ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q worker@84.252.128.120 -i ~/.ssh/id_ed25519"'

[kube_control_plane]
master

[etcd]
master

[kube_node]
worker-1
worker-2

[metallb_speaker]
worker-1
worker-2

[k8s_cluster:children]
kube_control_plane
kube_node
