name: Terraform CI/CD (Yandex Cloud)

on:
  push:
    branches:
      - main
    paths:
#      - 'preliminary/**'
      - 'implementation/**'
      - '.github/workflows/terraform.yml'

env:
  YC_SERVICE_ACCOUNT_KEY_FILE: ${{ github.workspace }}/key.json
  YC_CLOUD_ID: ${{ secrets.CLOUD_ID }}
  YC_FOLDER_ID: ${{ secrets.FOLDER_ID }}
  YC_BUCKET_NAME: ${{ secrets.YC_BUCKET_NAME }}
  YC_KEY_JSON: ${{ secrets.YC_KEY_JSON }}

jobs:
  # terraform-preliminary:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.7.0

  #     - name: Setup Python for YC CLI
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.x'

  #     - name: Install YC CLI
  #       run: pip install yandexcloud

  #     - name: Write YC key file
  #       run: echo '${{ secrets.YC_KEY_JSON }}' > $YC_SERVICE_ACCOUNT_KEY_FILE
      
  #     - name: Debug working directory
  #       run: |
  #         echo "Current directory: $(pwd)"
  #         ls -la

  #     - name: Terraform Init
  #       run: terraform init
  #       working-directory: preliminary

  #     - name: Terraform Validate
  #       run: terraform validate
  #       working-directory: preliminary

  #     - name: Terraform Plan
  #       working-directory: preliminary
  #       env:
  #         TF_VAR_service_account_key_file: ${{ env.YC_SERVICE_ACCOUNT_KEY_FILE }}
  #         TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
  #         TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
  #       run: terraform plan -out=tfplan

  #     - name: Terraform Apply
  #       if: github.ref == 'refs/heads/main'
  #       working-directory: preliminary
  #       env:
  #         TF_VAR_service_account_key_file: ${{ env.YC_SERVICE_ACCOUNT_KEY_FILE }}
  #         TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
  #         TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
  #       run: terraform apply -auto-approve tfplan

  terraform-implementation:
    runs-on: ubuntu-latest
  #  needs: terraform-preliminary
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      - name: Setup Python for YC CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install YC CLI
        run: pip install yandexcloud

      - name: Write YC key file
        run: echo '${{ secrets.YC_KEY_JSON }}' > $YC_SERVICE_ACCOUNT_KEY_FILE

      - name: Terraform Init
        run: terraform init
        working-directory: implementation

      - name: Terraform Validate
        run: terraform validate
        working-directory: implementation

      - name: Terraform Plan
        working-directory: implementation
        env:
          TF_VAR_service_account_key_file: ${{ env.YC_SERVICE_ACCOUNT_KEY_FILE }}
          TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: implementation
        env:
          TF_VAR_service_account_key_file: ${{ env.YC_SERVICE_ACCOUNT_KEY_FILE }}
          TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
        run: terraform apply -auto-approve tfplan
            
